# config.yaml

transport_mode: "stdio" # Options: "sse" or "stdio"

# For SSE mode, mcp_server_base_url and mcp_paths are required
# For stdio mode, both are optional and will be derived from command configuration if not specified
mcp_server_base_url: "http://localhost:8000"
listen_port: 8080
timeout_seconds: 10
mcp_paths: # Required in SSE mode, ignored in stdio mode (derived from command)
  - /messages/
  - /sse

# Subprocess configuration
command:
  enabled: true
  user_command: "npx -y @modelcontextprotocol/server-github" # User only needs to provide this part
  base_url: "http://localhost:8000" # Will be used for CORS and in the full command
  port: 8000 # Port for the MCP server
  sse_path: "/sse" # SSE endpoint path
  message_path: "/messages" # Messages endpoint path
  work_dir: "" # Working directory (optional)
  # env:                             # Environment variables (optional)
  #   - "NODE_ENV=development"

path_mapping:

cors:
  allowed_origins:
    - "http://localhost:5173"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
  allow_credentials: true

demo:
  org_name: "openmcpauthdemo"
  client_id: "N0U9e_NNGr9mP_0fPnPfPI0a6twa"
  client_secret: "qFHfiBp5gNGAO9zV4YPnDofBzzfInatfUbHyPZvM0jka"
