# config.yaml

# Common configuration for all transport modes
listen_port: 8080
base_url: "http://localhost:3001" # Base URL for the MCP server
port: 3001 # Port for the MCP server
timeout_seconds: 10

# Path configuration
paths:
  sse: "/sse" # SSE endpoint path
  messages: "/messages/" # Messages endpoint path
  streamable_http: "/mcp" # MCP endpoint path

# Transport mode configuration
transport_mode: "sse" # Options: "sse" or "stdio"

# stdio-specific configuration (used only when transport_mode is "stdio")
stdio:
  enabled: true
  user_command: "npx -y @modelcontextprotocol/server-github"
  work_dir: "" # Working directory (optional)
  # env:                           # Environment variables (optional)
  #   - "NODE_ENV=development"

# Path mapping (optional)
path_mapping:

# CORS configuration
cors:
  allowed_origins:
    - "http://127.0.0.1:6274"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "mcp-protocol-version"
  allow_credentials: true

# Demo configuration for Asgardeo
demo:
  org_name: "openmcpauthdemo"
  client_id: "N0U9e_NNGr9mP_0fPnPfPI0a6twa"
  client_secret: "qFHfiBp5gNGAO9zV4YPnDofBzzfInatfUbHyPZvM0jka"

# Protected resource metadata
resource_identifier: http://localhost:3000
scopes_supported:
  - get-alerts
  - get-forecast
authorization_servers:
  - https://idp.example.com
jwks_uri: https://idp.example.com/.well-known/jwks.json
bearer_methods_supported:
  - header
  - body
  - query