# config.yaml

mcp_server_base_url: ""
listen_port: 8080
timeout_seconds: 10

mcp_paths:
  - /messages/
  - /sse

path_mapping:
  /token: /token
  /register: /register
  /authorize: /authorize
  /.well-known/oauth-authorization-server: /.well-known/oauth-authorization-server

cors:
  allowed_origins:
    - ""
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
  allow_credentials: true

demo:
  org_name: "openmcpauthdemo"
  client_id: "N0U9e_NNGr9mP_0fPnPfPI0a6twa"
  client_secret: "qFHfiBp5gNGAO9zV4YPnDofBzzfInatfUbHyPZvM0jka"

asgardeo:
  org_name: "<org_name>"
  client_id: "<client_id>"
  client_secret: "<client_secret>"

default:
  base_url: "<base_url>"
  jwks_url: "<jwks_url>"
  path:
    /.well-known/oauth-authorization-server:
      response:
        issuer: "<issuer>"
        jwks_uri: "<jwks_uri>"
        authorization_endpoint: "<authorization_endpoint>" # Optional
        token_endpoint: "<token_endpoint>" # Optional
        registration_endpoint: "<registration_endpoint>" # Optional
        response_types_supported: 
          - "code"
        grant_types_supported:
          - "authorization_code"
          - "refresh_token"
        code_challenge_methods_supported:
          - "S256"
          - "plain"  
    /authroize:
      addQueryParams:
        - name: "<name>"
          value: "<value>"
    /token:
      addBodyParams:
        - name: "<name>"
          value: "<value>"
    /register:
      addBodyParams:
        - name: "<name>"
          value: "<value>"

